name: smart_tourism
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter 
  get: ^4.6.6
  intl: ^0.18.1
  device_preview: ^1.1.0
  flutter_screenutil: ^5.9.0
  page_transition: ^2.1.0
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/Assets/Images/logo.png"

flutter_assets:
  assets_path: lib/Assets/Images/
  output_path: lib/Feature/constants
  filename: ImagesForFullApp.dart
  field_prefix:  
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/Assets/Images/
    - lib/Assets/Database/
    - lib/Assets/Fonts/
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: lib/Assets/Fonts/Cairo-Regular.ttf
  #       - asset: lib/Assets/Fonts/Cairo-Bold.ttf
  #         weight: 700
  #       - asset: lib/Assets/Fonts/Cairo-Medium.ttf

  #   - family: Quran
  #     fonts:
  #       - asset: lib/Assets/Fonts/Quran.ttf

  #   - family: ArefRuqaa
  #     fonts:
  #       - asset: lib/Assets/Fonts/ArefRuqaa-Regular.ttf
  #       - asset: lib/Assets/Fonts/ArefRuqaa-Bold.ttf
  #         weight: 700

  #   - family: NotoNastaliqUrdu
  #     fonts:
  #       - asset: lib/Assets/Fonts/NotoNastaliqUrdu-Bold.ttf
  #         weight: 700
  #       - asset: lib/Assets/Fonts/NotoNastaliqUrdu-Regular.ttf
  