name: smart_tourism
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  bloc: ^8.1.2
  device_preview: ^1.1.0
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  awesome_dialog: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_offline: ^3.0.0
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.6.0
  get: ^4.6.6
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2
  
  

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Assets/Images/logo.png"

flutter_assets:
  assets_path: Assets/Images/
  output_path: lib/constants
  filename: ImagesForFullApp.dart
  field_prefix: null
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - Assets/Images/
    - Assets/Database/
    - Assets/Fonts/
  fonts:
    - family: Master
      fonts:
         - asset: Assets/Fonts/Poppins-Regular.ttf
         - asset: Assets/Fonts/Poppins-Bold.ttf
    # - family: Noto
    #   fonts:
    #     - asset: Assets/Fonts/NotoNastaliqUrdu-Bold.ttf
    #     - asset: Assets/Fonts/NotoNastaliqUrdu-Regular.ttf
    - family: Rubik
      fonts:
        - asset: Assets/Fonts/Rubik-Bold.ttf
        - asset: Assets/Fonts/Rubik-Regular.ttf
    - family: Play   
      fonts:
        - asset: Assets/Fonts/PlaypenSans-Bold.ttf
        - asset: Assets/Fonts/PlaypenSans-Regular.ttf 
